var nameList = [
    'Time', 'Past', 'Future', 'Dev',
    'Fly', 'Flying', 'Soar', 'Soaring', 'Power', 'Falling',
    'Fall', 'Jump', 'Cliff', 'Mountain', 'Rend', 'Red', 'Blue',
    'Green', 'Yellow', 'Gold', 'Demon', 'Demonic', 'Panda', 'Cat',
    'Kitty', 'Kitten', 'Zero', 'Memory', 'Trooper', 'XX', 'Bandit',
    'Fear', 'Light', 'Glow', 'Tread', 'Deep', 'Deeper', 'Deepest',
    'Mine', 'Your', 'Worst', 'Enemy', 'Hostile', 'Force', 'Video',
    'Game', 'Donkey', 'Mule', 'Colt', 'Cult', 'Cultist', 'Magnum',
    'Gun', 'Assault', 'Recon', 'Trap', 'Trapper', 'Redeem', 'Code',
    'Script', 'Writer', 'Near', 'Close', 'Open', 'Cube', 'Circle',
    'Geo', 'Genome', 'Germ', 'Spaz', 'Shot', 'Echo', 'Beta', 'Alpha',
    'Gamma', 'Omega', 'Seal', 'Squid', 'Money', 'Cash', 'Lord', 'King',
    'Duke', 'Rest', 'Fire', 'Flame', 'Morrow', 'Break', 'Breaker', 'Numb',
    'Ice', 'Cold', 'Rotten', 'Sick', 'Sickly', 'Janitor', 'Camel', 'Rooster',
    'Sand', 'Desert', 'Dessert', 'Hurdle', 'Racer', 'Eraser', 'Erase', 'Big',
    'Small', 'Short', 'Tall', 'Sith', 'Bounty', 'Hunter', 'Cracked', 'Broken',
    'Sad', 'Happy', 'Joy', 'Joyful', 'Crimson', 'Destiny', 'Deceit', 'Lies',
    'Lie', 'Honest', 'Destined', 'Bloxxer', 'Hawk', 'Eagle', 'Hawker', 'Walker',
    'Zombie', 'Sarge', 'Capt', 'Captain', 'Punch', 'One', 'Two', 'Uno', 'Slice',
    'Slash', 'Melt', 'Melted', 'Melting', 'Fell', 'Wolf', 'Hound',
    'Legacy', 'Sharp', 'Dead', 'Mew', 'Chuckle', 'Bubba', 'Bubble', 'Sandwich', 'Smasher', 'Extreme', 'Multi', 'Universe', 'Ultimate', 'Death', 'Ready', 'Monkey', 'Elevator', 'Wrench', 'Grease', 'Head', 'Theme', 'Grand', 'Cool', 'Kid', 'Boy', 'Girl', 'Vortex', 'Paradox'
];

export function generateNames() {
    var finalName = nameList[Math.floor(Math.random() * nameList.length)];
    return finalName;
};

const messages = [
    "Hello!",
    "How are you doing?",
    "Nice to meet you!",
    "What's up?",
    "React is awesome!",
    "Let's build something cool!",
    "This chat is fun!",
    "I'm learning JavaScript!",
    "How's your day going?",
    "Anyone up for a coding challenge?",
    "Just finished a new project!",
    "Has anyone tried Next.js?",
    "I love working with Redux!",
    "Frontend development is amazing!",
    "Does anyone have a good API recommendation?",
    "I'm debugging my code... again! 😅",
    "What are you currently working on?",
    "Vue vs React, what's your pick?",
    "Dark mode or light mode?",
    "Time for a coffee break! ☕",
    "Which JavaScript framework do you prefer?",
    "Just started learning TypeScript!",
    "This bug is driving me crazy! 😤",
    "Coding at midnight hits different!",
    "What’s your favorite coding playlist?",
    "Does anyone use Tailwind CSS?",
    "What’s the best way to manage state in React?",
    "I finally fixed that bug! 🎉",
    "Frontend or Backend?",
    "I need a good React tutorial!",
    "Anyone here a full-stack developer?",
    "What’s your dream tech job?",
    "GraphQL vs REST API, thoughts?",
    "Which UI library do you recommend?",
    "Git merge conflicts… again. 😭",
    "What’s your favorite VS Code extension?",
    "This React app is getting huge!",
    "Any tips for optimizing React performance?",
    "What’s your best debugging trick?",
    "Unit testing is harder than I thought!",
    "AI is changing web development!",
    "React server components are interesting!",
    "Who else loves open-source projects?",
    "Just deployed my first project! 🚀",
    "Firebase vs Supabase, which one do you use?",
    "I need help with my portfolio website!",
    "Do you prefer working solo or in a team?",
    "Remote work or office?",
    "What’s your favorite coding meme?",
    "Learning a new programming language is exciting!",
    "This API response is so slow! ⏳",
    "Time for a break, my brain is fried! 🤯",
    "What’s your go-to tech blog?",
    "Anyone into Web3 development?",
    "React Hooks changed everything!",
    "Can someone explain closures in JavaScript?",
    "Coding with coffee is a must! ☕",
    "Let’s build something cool together!",
    "I just refactored my code, and now it’s broken! 😵",
    "CSS Grid or Flexbox?",
    "Who else loves dark mode?",
    "My laptop fan sounds like a jet engine! ✈️",
    "When will I finally understand recursion? 😅",
    "Hackathons are so much fun!"
];


export const generateRandomMessage = () => {
    return messages[Math.floor(Math.random() * messages.length)];
};
